### ISSUE TITLE
你好，请问为什么在fragment里面图片不能沉浸状态栏额？

### ISSUE THREAD

**Issue by i91h1r** [anzewei/Android-DesignEx#1]
style 和布局的代码一样，但是状态栏的颜色不能透明，这是为什么额？

**Comment by waldenana** [comment]
状态栏不透明 应该是style不对，这个一定要加
`android:windowTranslucentStatus=true`
另外layout需要设置  
`android:fitsSystemWindows="false"`
再有一点是沉浸状态栏需要4.4之后的版本才可以
