### ISSUE TITLE
下拉图片放大到一定位置拉不动了

### ISSUE THREAD

**Issue by Bobyang912** [anzewei/Android-DesignEx#5]
下拉图片放大的时候，拉倒一定位置就拉不动的，这个能不能处理自然一点，还可以继续往下拉呢

**Comment by waldenana** [comment]
/**
     * @return 下拉的最大值
     */
    private int getMaxRange() {
        return mContent != null ? mContent.getHeight() / 2 : 0;
    }
你只需要修改这个位置
