### ISSUE TITLE
拉伸到最大时，图片铺不满布局

### ISSUE THREAD

**Issue by libin1993** [anzewei/Android-DesignEx#8]
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/white">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"
        app:layout_behavior="android.support.design.widget.ParallaxScaleBehavior">

        <com.github.anzewei.design.CollapsingCenterLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:fitsSystemWindows="true"
            app:layout_scrollFlags="scroll|exitUntilCollapsed|snap">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_collapseMode="parallax">

                <ImageView
                    android:id="@+id/img_designer_works"
                    android:layout_width="match_parent"
                    android:layout_height="250dp"
                    android:scaleType="centerCrop"
                    android:src="@mipmap/icon_test"/>

                <TextView
                    android:id="@+id/tv_designer_works"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerInParent="true"
                    android:text="dcdcsdsdddcdcssdc"
                    android:textColor="@android:color/white"
                    android:textSize="18sp"/>
            </RelativeLayout>
        </com.github.anzewei.design.CollapsingCenterLayout>

        <com.flyco.tablayout.SlidingTabLayout
            android:id="@+id/tab_designer_works"
            android:layout_width="match_parent"
            android:layout_height="40dp"
            android:background="@android:color/white"
            app:tl_indicator_color="#414141"
            app:tl_indicator_height="2.5dp"
            app:tl_indicator_margin_bottom="5dp"
            app:tl_indicator_width_equal_title="true"
            app:tl_tab_space_equal="true"
            app:tl_textBold="SELECT"
            app:tl_textSelectColor="#4F4F4F"
            app:tl_textUnselectColor="#7A7A7A"
            app:tl_textsize="12sp">
        </com.flyco.tablayout.SlidingTabLayout>

    </android.support.design.widget.AppBarLayout>

    <android.support.v4.view.ViewPager
        android:id="@+id/vp_designer_works"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">
    </android.support.v4.view.ViewPager>

</android.support.design.widget.CoordinatorLayout>

**Comment by libin1993** [comment]
我发现是因为加了TabLayout的问题，请问怎么解决呢？

**Comment by waldenana** [comment]
刚刚更新了0.5 版本，修复了这个问题
